In [1]:
import numpy as np

In [4]:
arr1 = np.arange(10, 51)
print(arr1)
print("\n")
arr2 = np.random.rand(3, 3)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


[[0.43116921 0.94501589 0.22492179]
 [0.52494608 0.88709583 0.38977686]
 [0.30653739 0.2110474  0.8195518 ]]


In [8]:
shape = arr2.shape
print(shape)
size = arr2.size
print(size)
dtype = arr2.dtype
print(dtype)

(3, 3)
9
float64


3.Basic Operations

In [13]:
arr_plus_5 = arr1 + 5
print(arr_plus_5)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
prod = array1 * array2
print(prod)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 5 12]
 [21 32]]


In [15]:
arr3 = np.arange(1, 26).reshape(5, 5)
print(arr3)
print("\n")
first_row = arr3[0, :]
print(first_row)
print("\n")
last_column = arr3[:, -1]
print(last_column)
print("\n")
subarr = arr3[:3, :2]
print(subarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[1 2 3 4 5]


[ 5 10 15 20 25]


[[ 1  2]
 [ 6  7]
 [11 12]]


In [17]:
arr4 = np.random.randint(1,101,10)
print(arr4)
max_val = arr4.max()
min_val = arr4.min()
mean_val = arr4.mean()
std_val = arr4.std()
print(max_val,"\n",min_val,"\n",mean_val,"\n",std_val)

[69 18  6 97  5 61 85 23 13 16]
97 
 5 
 39.3 
 33.181470732925625


In [19]:
arr5 = np.arange(1, 13).reshape(3, 4)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
matrix_ones = np.ones((3, 3))
print(matrix_ones)
print("\n")
result = matrix_ones + np.array([1, 2, 3])
print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [28]:
array1 = np.random.randint(1, 51, size=15)
print(array1)
print("\n")

for num in array1:
    if num % 5 == 0:  
        print(num)

[20 26 42 32 41  5 26 34 16 39 46 35  8 39 20]


20
5
35
20


In [29]:
matA = np.array([[9, 2], [3, 7]])
matB = np.array([[1, 4], [5, 8]])
mat_mul = np.dot(matA, matB)
print(mat_mul)

[[19 52]
 [38 68]]


In [32]:
array2 = np.arange(1, 17).reshape(4, 4)
print(array2)
print("\n")
rows = [0,1,2,3]
columns = [0,1,2,3]
print("Diagonal elements are:",array2[rows,columns])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Diagonal elements are: [ 1  6 11 16]
